apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment-chatapp
  namespace: chat-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: chatapp-backend
        image: anilvcr/chatapp-backend:latest

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

        ports:
        - containerPort: 5001

        env:
        - name: NODE_ENV
          value: "production"

        - name: MONGODB_URI
          value: "mongodb://mongoadmin:mongoadmin@mongodb:27017/dbname?authSource=admin"

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secret
              key: jwt

        - name: PORT
          value: "5001"